### ISSUE TITLE
Cancel Button adds new record

### ISSUE THREAD

**Issue by mjanofsky** [RubenHeeren/CRUD30Mins#1]
I noticed that clicking the Cancel button on the Create page does create/update the record.  I'm guessing it's the binding?

**Comment by RubenHeeren** [comment]
Thanks for bringing that up. I've noticed it too on other projects. It can be fixed by adding type="button" to non-submit buttons in EditForms.

 <button type="button" @onclick="() => DoStuff()" class="btn btn-lg btn-secondary ms-4">
